### ISSUE TITLE
Design this ui

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/interactive-js-website#1]
Todo :- 
- [ ] duplicate the ui using html and css
- [ ] make chnges in the `index.html`

### Desktop View :- 
![image](https://user-images.githubusercontent.com/115569958/198925086-79eed121-a5d9-4721-8306-583a6d3bc6e6.png)

### Mobile View :- 
![image](https://user-images.githubusercontent.com/115569958/198925149-33f728e3-705c-4a7f-a63a-5be44dc11eba.png)

**Comment by amitanshusahu** [comment]
i can do that .. 😄

**Comment by osbc2022** [comment]
Awesome :star_struck: !!
